### PR TITLE
Isomorphic optimization

### PR DESCRIPTION
**Pull request by ascariandrea**
I had some issues when I used for isomorphic environment, so I refactor the code to avoid them:
- Removed the `setState` usage, replacing by declaring local scoped variables
- Move the `this.props.onChoice` call in `componentDidMount` to be sure it's called on mounted component.
- General refactor.

### CODE REVIEW

**Comment by olahol** [comment]
What problems did you have with the isomorphic usage? The setState in `componentWillMount` should always fire before the first render.

**Comment by ascariandrea** [comment]
My issue is related to this one: https://github.com/facebook/react/issues/1866

**Comment by olahol** [comment]
I see, is this specific to 0.11? `react-ab` requires ^0.13

**Comment by ascariandrea** [comment]
Yep, but the issue is still present: https://github.com/facebook/react/issues/3620

**Comment by olahol** [comment]
Ok, thank you, I will check this after work.

**Comment by ascariandrea** [comment]
You're welcome, I hope this helps :)

**Comment by olahol** [comment]
I have implement your suggestion in the branch [remove-state](https://github.com/olahol/react-ab/tree/remove-state). Could you take a look and check if it works for you?

**Comment by ascariandrea** [comment]
I think this line still breaks:
https://github.com/olahol/react-ab/blob/remove-state/react-ab.js#L132

Can I ask you a question?
Why this strange code format?

**Comment by olahol** [comment]
Why would this break? I feel like `onChoice` needs to be called everytime a variant is determined.

> Why this strange code format?

This is just the way I write Javascript, having the commas at the beginning is a habit i picked up from Haskell.

**Comment by ascariandrea** [comment]
I think you need to call it on `componentDidMount`to be sure also the parent component is mounted.

**Comment by olahol** [comment]
Do you think the `onChoice` should only be fired on the client side? I'm not sure that should be the case.

**Pull request closed without merging**
